alias: AI Weather Report
description: >-
  Fetches hourly weather forecasts, uses AI to summarize them into an emoji-rich
  report, and stores it in an input text helper every 6 hours.
triggers:
  - trigger: time_pattern
    hours: /6
conditions: []
actions:
  - action: weather.get_forecasts
    metadata: {}
    target:
      entity_id: weather.thuis
    data:
      type: hourly
    response_variable: hourly_forecast
  - variables:
      forecast_list: "{{ hourly_forecast['weather.thuis'].forecast | default([]) }}"
  - action: ai_task.generate_data
    metadata: {}
    data:
      task_name: hourly forecast
      entity_id: ai_task.openai_ai_task
      instructions: >-
        Hier is het weer voor de aankomende uren in JSON: {{ forecast_list |
        tojson }}


        maak hier een weerbericht van in 150 letters. maak gebruik van emojis.
    response_variable: ai_response
  - action: input_text.set_value
    metadata: {}
    target:
      entity_id: input_text.ai_respone
    data:
      value: "{{ ai_response.data | default('Geen Data Beschikbaar.') }}"
mode: single
