blueprint:
  domain: automation
  name: "\U0001F508️ Volume Controle 3.0"
  author: r3mcos3
  source_url: https://github.com/r3mcos3/blueprints/blob/main/volumecontrol/volume_control3.yaml
  homeassistant:
    min_version: 2024.3.0
  description: "Blueprint to automate all your speakers \U0001F508️\n\n\U0001F4E6️
    Version: 2.0\n"
  input:
    media:
      name: "\U0001F4FB️ Media Players"
      description: '`Speakers`


        Speakers to use.

        '
      default: []
      selector:
        target:
          entity:
          - domain:
            - media_player
    scheduler:
      name: "\U0001F5D3️ Scheduler"
      description: '`Scheduler`


        for more information about schedulers click [here](https://www.home-assistant.io/integrations/schedule/)

        to make your scheduler click [here](https://my.home-assistant.io/redirect/helpers/).

        '
      default: []
      selector:
        entity:
          filter:
          - domain:
            - schedule
          multiple: false
    volume_up:
      name: "\U0001F50A Volume Up Level"
      description: '`Volume High Setting`


        The volume goes to this level when the scheduler goes to on

        '
      default: 0.6
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider
    volume_down:
      name: "\U0001F508️ Volume Down Level"
      description: '`Volume Low Setting`


        The volume goes to this level when the scheduler goes to off

        '
      default: 0.2
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider
    custom_action:
      name: "\U0001F3AC Custom Action"
      description: '`Custom Action` `Optional`


        This custom action gets executed if scheduler get to ''on'' or ''off''

        '
      default:
      selector:
        action: {}
mode: single
trigger:
- platform: state
  entity_id: !input scheduler
  to: 'on'
  id: aan
- platform: state
  entity_id: !input scheduler
  to: 'off'
  id: uit
action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - aan
    sequence:
    - service: media_player.volume_set
      target: !input media
      data:
        volume_level: !input volume_up
  - conditions:
    - condition: trigger
      id:
      - uit
    sequence:
    - service: media_player.volume_set
      target: !input media
      data:
        volume_level: !input volume_down
- if:
  - condition: template
    value_template: '{{ input_custom_action != none }}'
  then: !input custom_action
